
extent:
 lonmin : 31
 lonmax : 45
 latmin : 10
 latmax : 31

chl_url : http://oceandata.sci.gsfc.nasa.gov/cgi/getfile

crs : +proj=longlat +datum=WGS84

navalue : 32767

chl_file_suffix : .L3m_8D_CHL_chlor_a_9km.bz2